# **Numpy Practice**

In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
type(arr)

numpy.ndarray

## How to Find Array Which Dimention

In [5]:
arr.ndim

1

In [6]:
arr_2=np.array([[1,2,3,4,5],[5,4,3,2,1],[3,2,1,4,5]])

In [7]:
print(arr_2)

[[1 2 3 4 5]
 [5 4 3 2 1]
 [3 2 1 4 5]]


In [8]:
arr_2.ndim

2

## How to Check Size Of Array

In [9]:
arr_2.size

15

## How to Check Row and Column an Array

In [10]:
arr_2.shape # (row,column)

(3, 5)

## How to Check Data Type of an Array

In [11]:
arr_2.dtype

dtype('int64')

In [12]:
mat=np.ones((3,4)) # ones matrix create in built function in numpy in float .

In [13]:
print(mat)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
matrix=np.ones((4,4), dtype= int) # convert into float to another data type.

In [15]:
print(matrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [16]:
mat_1=np.zeros((4,6)) # zeros matrix create in built function in numpy in float.

In [17]:
print(mat_1)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [18]:
matrix_1=np.zeros((4,5), dtype= int)

In [19]:
print(matrix_1)   # convert into float to another data type.

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [20]:
mt=np.zeros((4,4), dtype=bool) # convert into boolean data type ,0 = false or 1 = true .

In [21]:
print(mt)

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


In [22]:
mt_1=np.ones((4,4), dtype=bool) # convert into boolean data type ,0 = false or 1 = true .

In [23]:
print(mt_1)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


# **NUMPY FUNCTION**

##  1. **arange( )**

In [24]:
# np.arange(start,end,steps)

In [25]:
a=np.arange(1,13)

In [26]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
b=np.arange(1,20,2) # odd number 

In [28]:
print(b)

[ 1  3  5  7  9 11 13 15 17 19]


## 2. **linspace( )**

In [29]:
li=np.linspace(1,4,7)

In [30]:
print(li)

[1.  1.5 2.  2.5 3.  3.5 4. ]


## 3. **reshape( )**

In [31]:
arr_1d=np.arange(1,13) # creating one dimensional array

In [32]:
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [33]:
arr_2d=arr_1d.reshape(2,6) # converting into one dimensional to two dimensional.

In [34]:
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [35]:
arr_2d=arr_1d.reshape(3,4) # converting into one dimensional to two dimensional.

In [36]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [37]:
arr_3d=arr_1d.reshape(2,3,2)   # converting into one dimensional to three dimensional.

In [38]:
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [39]:
ar=np.arange(1,13).reshape(2,6)

In [40]:
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# 4. **reval( )**

In [41]:
re=np.ravel(arr_2d) # reval convert multi-dimensional array to one dimensional.

In [42]:
print(re)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# 5. **flatten()**

In [43]:
arr_2d.flatten() # flatten convert multi-dimensional array to one dimensional.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# 6. **transpose( )**

In [44]:
tr=np.transpose(ar) # It convert row into column.

In [45]:
print(tr)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [46]:
ar.T # also use T.

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# **Mathematic Operation Using Numpy**

In [47]:
arr1=np.arange(1,10).reshape(3,3)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
arr2=np.arange(10,19).reshape(3,3)
print(arr2)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [49]:
arr3=arr1+arr2 # adding two matrix

In [50]:
print(arr3)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [51]:
arr4=np.add(arr1,arr2) # adding two matrix using in built function.

In [52]:
print(arr4)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [53]:
arr5=np.subtract(arr1,arr2) # subtract  two matrix using in built function.

In [54]:
print(arr5)

[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]


In [55]:
arr6=np.divide(arr1,arr2) # divide two matrix using in built function.

In [56]:
print(arr6)

[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]


In [57]:
arr7=np.multiply(arr1,arr2) # multiply two matrix using in built function.

In [58]:
print(arr7)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [59]:
arr7.max()

162

In [60]:
arr7.min()

10

In [61]:
arr7.argmax()

8

In [62]:
arr7.argmin()

0

In [63]:
arr7.max(axis=0) # Find maximum value in column , 0 = column.

array([112, 136, 162])

In [64]:
arr7.max(axis=1) # Find maximum value in row , 1= row.

array([ 36,  90, 162])

In [65]:
arr7.min(axis=0)  # Find minimum value in column , 0 = column.

array([10, 22, 36])

In [66]:
arr7.min(axis=1)  # Find minimum value in column , 0 = column.

array([ 10,  52, 112])

In [67]:
np.sum(arr7) # sum of the matrix.

690

In [68]:
np.sum(arr7,axis=0)

array([174, 228, 288])

In [69]:
np.sum(arr7,axis=1)

array([ 68, 212, 410])

In [70]:
np.mean(arr7)

76.66666666666667

In [71]:
np.sqrt(arr7)

array([[ 3.16227766,  4.69041576,  6.        ],
       [ 7.21110255,  8.36660027,  9.48683298],
       [10.58300524, 11.66190379, 12.72792206]])

In [72]:
np.std(arr7) # standard division.

49.40535283639708

In [73]:
np.log(2)

0.6931471805599453

In [74]:
np.log(arr7)

array([[2.30258509, 3.09104245, 3.58351894],
       [3.95124372, 4.24849524, 4.49980967],
       [4.71849887, 4.91265489, 5.08759634]])

In [75]:
np.exp(arr7) # exponent find .

array([[2.20264658e+04, 3.58491285e+09, 4.31123155e+15],
       [3.83100800e+22, 2.51543867e+30, 1.22040329e+39],
       [4.37503945e+48, 1.15890954e+59, 2.26832912e+70]])

In [76]:
np.log10(2)

0.3010299956639812

In [77]:
np.tan(3)

-0.1425465430742778

In [78]:
np.sin(989)

0.5660330877786267

In [79]:
np.cos(89)

0.5101770449416689